project:
  type: website
  output-dir: docs

website:
  title: "carolynrothmann.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: WQ.qmd
        text: Water Quality
    
      
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

